### ISSUE TITLE
the mAP of training

### ISSUE THREAD

**Issue by jokerchu123** [HamPerdredes/SOOD#6] opened 2023-06-13 01:39 UTC
### **Thank you for your wonderful work!  However, I try to train at a scale of ten percent and did not achieve the level of effectiveness mentioned in the paper.The configuration file I used is as follows.**

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.8
MMRotate: 0.3.4+962c9a6
------------------------------------------------------------

2023-06-12 02:33:39,541 - mmrotate - INFO - Distributed training: True
2023-06-12 02:33:40,760 - mmrotate - INFO - Config:
evaluation = dict(
    interval=3200,
    metric='mAP',
    type='SubModulesDistEvalHook',
    save_best='mAP')
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[120000, 160000])
runner = dict(type='IterBasedRunner', max_iters=180000)
checkpoint_config = dict(interval=3200, by_epoch=False, max_keep_ckpts=2)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
detector = dict(
    type='SemiRotatedFCOS',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5,
        relu_before_extra_convs=True),
    bbox_head=dict(
        type='SemiRotatedFCOSHead',
        num_classes=16,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        center_sampling=True,
        center_sample_radius=1.5,
        norm_on_bbox=True,
        centerness_on_reg=True,
        separate_angle=False,
        scale_angle=True,
        bbox_coder=dict(type='DistanceAnglePointCoder', angle_version='le90'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='RotatedIoULoss', loss_weight=1.0),
        loss_centerness=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    train_cfg=None,
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))
angle_version = 'le90'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
dataset_type = 'DebugDOTADataset'
src_data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='DebugDOTADataset',
        ann_file='/public/home/chuyanhao/DOTA_semi/train/labelTxt/',
        img_prefix='/public/home/chuyanhao/DOTA_semi/train/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(1024, 1024)),
            dict(type='RRandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    val=dict(
        type='DebugDOTADataset',
        ann_file='/public/home/chuyanhao/DOTA_semi/val/labelTxt/',
        img_prefix='/public/home/chuyanhao/DOTA_semi/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    test=dict(
        type='DebugDOTADataset',
        ann_file='/public/home/chuyanhao/DOTA_semi/val/labelTxt/',
        img_prefix='/public/home/chuyanhao/DOTA_semi/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')))
custom_imports = dict(imports=['ssad'], allow_failed_imports=False)
sup_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(type='ExtraAttrs', tag='sup_weak'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_filename', 'ori_shape', 'img_shape',
                   'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                   'img_norm_cfg', 'tag'))
]
common_pipeline = [
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'],
        meta_keys=('filename', 'ori_filename', 'ori_shape', 'img_shape',
                   'pad_shape', 'scale_factor', 'flip', 'flip_direction',
                   'img_norm_cfg', 'tag'))
]
strong_pipeline = [
    dict(type='DTToPILImage'),
    dict(
        type='DTRandomApply',
        operations=[
            ColorJitter(
                brightness=(0.6, 1.4),
                contrast=(0.6, 1.4),
                saturation=(0.6, 1.4),
                hue=(-0.1, 0.1))
        ],
        p=0.8),
    dict(type='DTRandomGrayscale', p=0.2),
    dict(
        type='DTRandomApply',
        operations=[dict(type='DTGaussianBlur', rad_range=[0.1, 2.0])]),
    dict(type='DTToNumpy'),
    dict(type='ExtraAttrs', tag='unsup_strong')
]
weak_pipeline = [
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(type='ExtraAttrs', tag='unsup_weak')
]
unsup_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadEmptyAnnotations', with_bbox=True),
    dict(
        type='STMultiBranch',
        unsup_strong=[
            dict(type='DTToPILImage'),
            dict(
                type='DTRandomApply',
                operations=[
                    ColorJitter(
                        brightness=(0.6, 1.4),
                        contrast=(0.6, 1.4),
                        saturation=(0.6, 1.4),
                        hue=(-0.1, 0.1))
                ],
                p=0.8),
            dict(type='DTRandomGrayscale', p=0.2),
            dict(
                type='DTRandomApply',
                operations=[dict(type='DTGaussianBlur', rad_range=[0.1,
                                                                   2.0])]),
            dict(type='DTToNumpy'),
            dict(type='ExtraAttrs', tag='unsup_strong')
        ],
        unsup_weak=[
            dict(type='RResize', img_scale=(1024, 1024)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='le90'),
            dict(type='ExtraAttrs', tag='unsup_weak')
        ],
        common_pipeline=[
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=('filename', 'ori_filename', 'ori_shape',
                           'img_shape', 'pad_shape', 'scale_factor', 'flip',
                           'flip_direction', 'img_norm_cfg', 'tag'))
        ],
        is_seq=True)
]
data = dict(
    samples_per_gpu=3,
    workers_per_gpu=3,
    train=dict(
        type='SemiDataset',
        sup=dict(
            type='DebugDOTADataset',
            ann_file=
            '/public/home/chuyanhao/split_ss_dota_v15/semi_train_10_labeled/annfiles',
            img_prefix=
            '/public/home/chuyanhao/split_ss_dota_v15/semi_train_10_labeled/images/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(type='RResize', img_scale=(1024, 1024)),
                dict(
                    type='RRandomFlip',
                    flip_ratio=[0.25, 0.25, 0.25],
                    direction=['horizontal', 'vertical', 'diagonal'],
                    version='le90'),
                dict(type='ExtraAttrs', tag='sup_weak'),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='Pad', size_divisor=32),
                dict(type='DefaultFormatBundle'),
                dict(
                    type='Collect',
                    keys=['img', 'gt_bboxes', 'gt_labels'],
                    meta_keys=('filename', 'ori_filename', 'ori_shape',
                               'img_shape', 'pad_shape', 'scale_factor',
                               'flip', 'flip_direction', 'img_norm_cfg',
                               'tag'))
            ],
            classes=('plane', 'baseball-diamond', 'bridge',
                     'ground-track-field', 'small-vehicle', 'large-vehicle',
                     'ship', 'tennis-court', 'basketball-court',
                     'storage-tank', 'soccer-ball-field', 'roundabout',
                     'harbor', 'swimming-pool', 'helicopter',
                     'container-crane')),
        unsup=dict(
            type='DebugDOTADataset',
            ann_file=
            '/public/home/chuyanhao/split_ss_dota_v15/semi_train_10_unlabeled/empty_annfiles',
            img_prefix=
            '/public/home/chuyanhao/split_ss_dota_v15/semi_train_10_unlabeled/images',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadEmptyAnnotations', with_bbox=True),
                dict(
                    type='STMultiBranch',
                    unsup_strong=[
                        dict(type='DTToPILImage'),
                        dict(
                            type='DTRandomApply',
                            operations=[
                                ColorJitter(
                                    brightness=(0.6, 1.4),
                                    contrast=(0.6, 1.4),
                                    saturation=(0.6, 1.4),
                                    hue=(-0.1, 0.1))
                            ],
                            p=0.8),
                        dict(type='DTRandomGrayscale', p=0.2),
                        dict(
                            type='DTRandomApply',
                            operations=[
                                dict(
                                    type='DTGaussianBlur',
                                    rad_range=[0.1, 2.0])
                            ]),
                        dict(type='DTToNumpy'),
                        dict(type='ExtraAttrs', tag='unsup_strong')
                    ],
                    unsup_weak=[
                        dict(type='RResize', img_scale=(1024, 1024)),
                        dict(
                            type='RRandomFlip',
                            flip_ratio=[0.25, 0.25, 0.25],
                            direction=['horizontal', 'vertical', 'diagonal'],
                            version='le90'),
                        dict(type='ExtraAttrs', tag='unsup_weak')
                    ],
                    common_pipeline=[
                        dict(
                            type='Normalize',
                            mean=[123.675, 116.28, 103.53],
                            std=[58.395, 57.12, 57.375],
                            to_rgb=True),
                        dict(type='Pad', size_divisor=32),
                        dict(type='DefaultFormatBundle'),
                        dict(
                            type='Collect',
                            keys=['img', 'gt_bboxes', 'gt_labels'],
                            meta_keys=('filename', 'ori_filename', 'ori_shape',
                                       'img_shape', 'pad_shape',
                                       'scale_factor', 'flip',
                                       'flip_direction', 'img_norm_cfg',
                                       'tag'))
                    ],
                    is_seq=True)
            ],
            filter_empty_gt=False,
            classes=('plane', 'baseball-diamond', 'bridge',
                     'ground-track-field', 'small-vehicle', 'large-vehicle',
                     'ship', 'tennis-court', 'basketball-court',
                     'storage-tank', 'soccer-ball-field', 'roundabout',
                     'harbor', 'swimming-pool', 'helicopter',
                     'container-crane'))),
    val=dict(
        type='DebugDOTADataset',
        ann_file='/public/home/chuyanhao/DOTA_semi/val/labelTxt/',
        img_prefix='/public/home/chuyanhao/DOTA_semi/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    test=dict(
        type='DebugDOTADataset',
        ann_file='/public/home/chuyanhao/DOTA_semi/val/labelTxt/',
        img_prefix='/public/home/chuyanhao/DOTA_semi/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
                 'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
                 'basketball-court', 'storage-tank', 'soccer-ball-field',
                 'roundabout', 'harbor', 'swimming-pool', 'helicopter',
                 'container-crane')),
    sampler=dict(
        train=dict(type='GroupMultiSourceSampler', sample_ratio=[2, 1])))
model = dict(
    type='RotatedSSTGDenseTeacher',
    model=dict(
        type='SemiRotatedFCOS',
        backbone=dict(
            type='ResNet',
            depth=50,
            num_stages=4,
            out_indices=(0, 1, 2, 3),
            frozen_stages=1,
            zero_init_residual=False,
            norm_cfg=dict(type='BN', requires_grad=True),
            norm_eval=True,
            style='pytorch',
            init_cfg=dict(
                type='Pretrained', checkpoint='torchvision://resnet50')),
        neck=dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            start_level=1,
            add_extra_convs='on_output',
            num_outs=5,
            relu_before_extra_convs=True),
        bbox_head=dict(
            type='SemiRotatedFCOSHead',
            num_classes=16,
            in_channels=256,
            stacked_convs=4,
            feat_channels=256,
            strides=[8, 16, 32, 64, 128],
            center_sampling=True,
            center_sample_radius=1.5,
            norm_on_bbox=True,
            centerness_on_reg=True,
            separate_angle=False,
            scale_angle=True,
            bbox_coder=dict(
                type='DistanceAnglePointCoder', angle_version='le90'),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0),
            loss_bbox=dict(type='RotatedIoULoss', loss_weight=1.0),
            loss_centerness=dict(
                type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
        train_cfg=None,
        test_cfg=dict(
            nms_pre=2000,
            min_bbox_size=0,
            score_thr=0.05,
            nms=dict(iou_thr=0.1),
            max_per_img=2000)),
    semi_loss=dict(
        type='RotatedSingleStageDTLoss',
        loss_type='pr_origin_p5',
        cls_loss_type='bce',
        dynamic_weight='50ang',
        aux_loss='ot_loss_norm',
        aux_loss_cfg=dict(clamp_ot=True)),
    train_cfg=dict(
        iter_count=0,
        burn_in_steps=6400,
        sup_weight=1.0,
        unsup_weight=1.0,
        weight_suppress='linear',
        logit_specific_weights=dict(),
        region_ratio=0.01),
    test_cfg=dict(inference_on='teacher'))
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='WeightSummary'),
    dict(type='MeanTeacher', momentum=0.9996, interval=1, start_steps=3200)
]
data_root = 'data/split_ss_dota_v15/'
classes = ('plane', 'baseball-diamond', 'bridge', 'ground-track-field',
           'small-vehicle', 'large-vehicle', 'ship', 'tennis-court',
           'basketball-court', 'storage-tank', 'soccer-ball-field',
           'roundabout', 'harbor', 'swimming-pool', 'helicopter',
           'container-crane')

###  **And the best result is as follows**
+--------------------+-------+--------+--------+-------+
| class              | gts   | dets   | recall | ap    |
+--------------------+-------+--------+--------+-------+
| plane              | 4801  | 10587  | 0.735  | 0.699 |
| baseball-diamond   | 374   | 3948   | 0.618  | 0.445 |
| bridge             | 784   | 10827  | 0.503  | 0.277 |
| ground-track-field | 319   | 2723   | 0.323  | 0.203 |
| small-vehicle      | 68080 | 164331 | 0.618  | 0.481 |
| large-vehicle      | 10631 | 45591  | 0.806  | 0.610 |
| ship               | 20201 | 61643  | 0.838  | 0.761 |
| tennis-court       | 1914  | 8878   | 0.894  | 0.787 |
| basketball-court   | 278   | 2087   | 0.457  | 0.401 |
| storage-tank       | 4787  | 11009  | 0.619  | 0.562 |
| soccer-ball-field  | 352   | 1860   | 0.398  | 0.245 |
| roundabout         | 292   | 5785   | 0.719  | 0.505 |
| harbor             | 4252  | 15721  | 0.495  | 0.339 |
| swimming-pool      | 957   | 11791  | 0.583  | 0.384 |
| helicopter         | 192   | 1788   | 0.344  | 0.227 |
| container-crane    | 27    | 1710   | 0.000  | 0.000 |
+--------------------+-------+--------+--------+-------+
| mAP                |       |        |        | 0.433 |
+--------------------+-------+--------+--------+-------+
2023-06-12 10:58:06,561 - mmrotate - INFO - 
+--------------------+-------+--------+--------+-------+
| class              | gts   | dets   | recall | ap    |
+--------------------+-------+--------+--------+-------+
| plane              | 4801  | 10405  | 0.729  | 0.691 |
| baseball-diamond   | 374   | 3633   | 0.599  | 0.442 |
| bridge             | 784   | 7182   | 0.477  | 0.286 |
| ground-track-field | 319   | 2314   | 0.323  | 0.196 |
| small-vehicle      | 68080 | 198583 | 0.611  | 0.453 |
| large-vehicle      | 10631 | 62238  | 0.803  | 0.584 |
| ship               | 20201 | 66182  | 0.831  | 0.746 |
| tennis-court       | 1914  | 14582  | 0.897  | 0.755 |
| basketball-court   | 278   | 3117   | 0.460  | 0.381 |
| storage-tank       | 4787  | 11984  | 0.599  | 0.510 |
| soccer-ball-field  | 352   | 1803   | 0.375  | 0.224 |
| roundabout         | 292   | 2981   | 0.702  | 0.513 |
| harbor             | 4252  | 15326  | 0.476  | 0.326 |
| swimming-pool      | 957   | 14186  | 0.575  | 0.376 |
| helicopter         | 192   | 1839   | 0.323  | 0.221 |
| container-crane    | 27    | 1754   | 0.000  | 0.000 |
+--------------------+-------+--------+--------+-------+
| mAP                |       |        |        | 0.419 |
+--------------------+-------+--------+--------+-------+
2023-06-12 10:58:06,803 - mmrotate - INFO - Saving best checkpoint to /public/home/chuyanhao/SOOD/SOOD_work_dir_6.11/best_0.432852_mAP.pth
2023-06-12 10:58:11,742 - mmrotate - INFO - Iter(val) [70400]	teacher.mAP: 0.4329, student.mAP: 0.4190

### **What issues are there with my configuration?**

**Comment by HamPerdredes** [comment] 2023-06-16 05:55
Let's check one by one. 
First, please make sure that he config you use is [this](https://github.com/HamPerdredes/SOOD/blob/main/configs/ssad_fcos/sood_fcos_dota15_10per.py) and makes no further modification. 
Second, for 10% setting, there should be 1825 labeled samples and 13924 unlabeled samples after spliting. Please make sure the nunbers are correct.
If above are fine, please try to run the [supervised baseline](https://github.com/HamPerdredes/SOOD/blob/main/configs/rotated_fcos/rotated_fcos_r50_fpn_10x_v15_10p_dota_le90.py) to see if it is a environment issue. If so, please provide the packages info via "pip list" and I'll see what can I do.

**Comment by jokerchu123** [comment] 2023-06-18 01:55
> Let's check one by one. First, please make sure that the config you use is [this](https://github.com/HamPerdredes/SOOD/blob/main/configs/ssad_fcos/sood_fcos_dota15_10per.py) and makes no further modification. Second, for 10% setting, there should be 1825 labeled samples and 13924 unlabeled samples after spliting. Please make sure the nunbers are correct. If above are fine, please try to run the [supervised baseline](https://github.com/HamPerdredes/SOOD/blob/main/configs/rotated_fcos/rotated_fcos_r50_fpn_10x_v15_10p_dota_le90.py) to see if it is a environment issue. If so, please provide the packages info via "pip list" and I'll see what can I do.

I have check the tips you mentioned one by one.Here is the [result](https://github.com/jokerchu123/SOOD_issue).
The semi-supervised config I used is correct and the images number is same as to yours.
Then I try to run the supervised baseline but it may not run well as the paper said.
Maybe there are some environmental problems and I also send the pip/conda list to the [result](https://github.com/jokerchu123/SOOD_issue).
Hope you can find the problem.

**Comment by HamPerdredes** [comment] 2023-06-19 03:16
I've noticed that the number of ground-truth in validation set seems not right. Compare to [yours](https://github.com/jokerchu123/SOOD_issue/blob/ddc1031386b2fc4d2ab303d20697288d7ba8b873/SOOD_log/SOOD_pytorch1.8.2.log#L1127), here is mine. Please make sure that the annotations are generated via DOTA-v1.5's official annotation file.
+--------------------+-------+
| class              | gts   | 
+--------------------+-------+
| plane              | 4478  | 
| baseball-diamond   | 354   | 
| bridge             | 788   | 
| ground-track-field | 214   | 
| small-vehicle      | 73488 | 
| large-vehicle      | 10284 | 
| ship               | 21783 | 
| tennis-court       | 1515  |
| basketball-court   | 287   |
| storage-tank       | 4819  |
| soccer-ball-field  | 243   |
| roundabout         | 287   |
| harbor             | 4185  | 
| swimming-pool      | 997   |
| helicopter         | 128   |
| container-crane    | 28    |

**Comment by jokerchu123** [comment] 2023-07-07 06:50
Sorry, after conducting multiple tests,  I have not achieved the desired results mentioned in the article. Here is my test result file [Test.log](https://github.com/jokerchu123/SOOD_issue/blob/main/Test.log).And I have noticed that the GC Loss may not seem to have the intended effect. Could you please let me know if there are any issues with my testing?

**Comment by HamPerdredes** [comment] 2023-07-10 10:35
According to the log file, the result achieves 47.9183 (compared to 48.63 in the paper). It seems that training and testing are fine, maybe try to train a little bit longer and try 20% and 30% settings. I guess that could be caused by environmental differences.

**Comment by BraveFigure** [comment] 2023-07-18 09:51
你好，我想问下那个学习率问题，初始学习率设置为0.0025，但是在训练中学习率达不到0.0025，只平衡在0.000025，跟我们一开始的学习率差了100倍。我想问问你们会这样吗 @HamPerdredes @jokerchu123

**Comment by Luo-Z13** [comment] 2023-08-25 03:45
> Sorry, after conducting multiple tests, I have not achieved the desired results mentioned in the article. Here is my test result file [Test.log](https://github.com/jokerchu123/SOOD_issue/blob/main/Test.log).And I have noticed that the GC Loss may not seem to have the intended effect. Could you please let me know if there are any issues with my testing?

Hi, why your 【 lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[180000])
runner = dict(type='IterBasedRunner', max_iters=180000)】
is different from the config in configs/_base_/schedules/schedule_1x.py
【learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=1)】?

**Comment by HamPerdredes** [comment] 2023-08-28 02:32
> > Sorry, after conducting multiple tests, I have not achieved the desired results mentioned in the article. Here is my test result file [Test.log](https://github.com/jokerchu123/SOOD_issue/blob/main/Test.log).And I have noticed that the GC Loss may not seem to have the intended effect. Could you please let me know if there are any issues with my testing?
> 
> Hi, why your 【 lr_config = dict( policy='step', warmup='linear', warmup_iters=500, warmup_ratio=0.3333333333333333, step=[180000]) runner = dict(type='IterBasedRunner', max_iters=180000)】 is different from the config in configs/_base_/schedules/schedule_1x.py 【learning policy lr_config = dict( policy='step', warmup='linear', warmup_iters=500, warmup_ratio=1.0 / 3, step=[8, 11]) runner = dict(type='EpochBasedRunner', max_epochs=12) checkpoint_config = dict(interval=1)】?

This is because subsequent config file such as [this](https://github.com/HamPerdredes/SOOD/blob/962c9a60ce9b82f99a6506d9e8542c32acbe5c2d/configs/ssad_fcos/sood_fcos_dota15_10per.py) will override the config with same name in parent config file, e.g., step and runner.

**Comment by HamPerdredes** [comment] 2023-08-28 02:33
I'd like to close this issue as there is no further questions, feel free to reopen it with any need.

**Closed by HamPerdredes** 2023-08-28 02:33 UTC
